/-
Copyright (c) 2025 Jonathan Konig. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jonathan Konig
-/
import Mathlib.Data.Nat.Basic
import Mathlib.Order.Basic
import Mathlib.Data.Fin.Tuple.Basic
import Mathlib.Logic.Relation

/-! # Finite partitions

This file contains several results around Injective and Surjective maps `Fin m → Fin n`
and the correspondance between a `Partition` -- characterized a surjective map -- and
equivalence relations `Fin n → Fin n → Prop`.
-/


namespace Fin

open Nat LT LE Relation

section

theorem fin_to_pred_not_inj {m : ℕ} (f : Fin (m + 1) → Fin m) : ¬ Function.Injective f := by
  apply Function.not_injective_iff.mpr
  induction m with
  | zero => exact (f 0).elim0
  | succ m ih =>
    let j := Fin.find (fun i ↦ (f i.castSucc).val = m)
    if hj : j = none then
      have hlt : ∀ i : Fin (m + 1), (f i.castSucc).val < m :=
        fun _ ↦ Nat.lt_of_le_of_ne (Nat.le_of_lt_succ (Fin.isLt _)) (Fin.find_eq_none_iff.mp hj _)
      specialize ih fun i ↦ ⟨(f i.castSucc).val, hlt i⟩
      apply ih.elim
      intro i ih
      apply ih.elim
      intro i' ih
      simp at ih
      apply Exists.intro i.castSucc
      apply Exists.intro i'.castSucc
      apply And.intro (Fin.eq_of_val_eq ih.left)
      apply Fin.ne_of_val_ne
      simp
      exact Fin.val_ne_of_ne ih.right
    else
      let hs₁ := Option.isSome_iff_ne_none.mpr (Ne.intro hj)
      let i₁ : Fin (m + 2) := (Option.get _ hs₁).castSucc
      let j' := Fin.find (fun i ↦ i ≠ i₁ ∧ (f i).val = m)
      if hj' : j' = none then
        have hlt : ∀ i : Fin (m + 2), i ≠ i₁ → (f i).val < m :=
          fun _ h ↦ Nat.lt_of_le_of_ne (Nat.le_of_lt_succ (Fin.isLt _))
            (not_and.mp (Fin.find_eq_none_iff.mp hj' _) h)
        specialize ih fun i ↦ ⟨(f (i₁.succAbove i)).val, hlt _ (i₁.succAbove_ne _)⟩
        apply ih.elim
        intro i ih
        apply ih.elim
        intro i' ih
        simp at ih
        apply Exists.intro (i₁.succAbove i)
        apply Exists.intro (i₁.succAbove i')
        apply And.intro (Fin.eq_of_val_eq ih.left)
        apply i₁.succAbove_right_inj.ne.mpr (Ne.intro ih.right)
      else
        have hs₂ := Option.isSome_iff_ne_none.mpr (Ne.intro hj')
        let i₂ : Fin (m + 2) := Option.get _ hs₂
        apply Exists.intro i₁
        apply Exists.intro i₂
        have h₁ : (f i₁).val = m := (Fin.find_eq_some_iff.mp (Option.some_get hs₁).symm).left
        have h₂ : i₂ ≠ i₁ ∧ (f i₂).val = m :=
          (Fin.find_eq_some_iff.mp (Option.some_get hs₂).symm).left
        apply And.intro (Fin.eq_of_val_eq (h₁.trans h₂.right.symm))
        exact h₂.left.symm

theorem le_of_inj {m n : ℕ} (f : Fin m → Fin n) : Function.Injective f → m ≤ n := by
  intro h
  induction m with
  | zero => exact Nat.zero_le _
  | succ m ih =>
    apply Nat.succ_le_of_lt
    apply le.lt_of_ne <| (ih _  <| h.comp <| Fin.castSucc_injective _)
    intro he
    obtain rfl : m = n := he
    exact fin_to_pred_not_inj f h

theorem ge_of_surj {m n : ℕ} (f : Fin m → Fin n) : Function.Surjective f → n ≤ m := by
  intro h
  match n with
  | 0 => exact Nat.zero_le _
  | n + 1 =>
    apply (Function.surjective_iff_hasRightInverse.mp h).elim
    intro g hid
    exact le_of_inj g (Function.injective_iff_hasLeftInverse.mpr (Exists.intro f hid))

theorem eq_of_bij {m n : ℕ} (f : Fin m → Fin n) : Function.Bijective f → m = n :=
  fun hf ↦ Nat.le_antisymm (le_of_inj _ hf.left) (ge_of_surj _ hf.right)

end

section

variable {n : ℕ} (r : Fin n → Fin n → Prop)

/-- This definition produces a subset of a relation `Fin n → Fin n → Prop` filtered
by lexicographic comparison on a pair of `Fin (n + 1)` values.
-/
def weaken_rel (i j : Fin (n + 1)) : Fin n → Fin n → Prop :=
  fun i' j' ↦ (i'.val < i.val ∨ i'.val = i.val ∧ j'.val < j.val) ∧ r i' j'

lemma weaken_succ (i : Fin n) (i' j' : Fin n) :
    weaken_rel r i.castSucc (last n) i' j' ↔ weaken_rel r i.succ 0 i' j' := by
  constructor
  · intro ⟨hw, hr⟩
    apply And.intro _ hr
    apply hw.elim
    · intro hl
      exact Or.inl (hl.trans (lt_succ_self _))
    · intro ⟨hl, _⟩
      exact Or.inl ((lt_succ_self _).trans_eq' hl)
  · intro ⟨hw, hr⟩
    apply And.intro _ hr
    apply hw.elim
    · intro hl
      if hi : i'.val = i.val then
        exact Or.inr ⟨hi, j'.isLt⟩
      else
        exact Or.inl ((le_of_lt_succ hl).lt_of_ne hi)
    · intro ⟨_, hn⟩
      exact False.elim (Nat.not_lt_zero _ hn)

lemma weaken_last (j : Fin (n + 1)) (i' j' : Fin n) : weaken_rel r (last n) j i' j' ↔ r i' j' :=
  Iff.intro And.right (⟨Or.inl i'.isLt, ·⟩)

end

/-- A `Partiton n` object is a representation of an equivalence class which maps each
object in a relation to a value corresponding to its equivalence class. The `size` property
identifies the number of equivalence classes generated by the `Partiton`. The `rep`
property maps each equivalence class identifier a representative member of the equivalence
class. The `rinv` property ensures that `map` is surjective, and the `min` and `mono`
properties together ensure that a `Partition n` object is uniquely identified by the
equivalence relation is generates -- `Partition.mapEq`.
-/
structure Partition (n : ℕ) where
  size : Fin (n + 1)
  map : Fin n → Fin size.val
  rep : Fin size.val → Fin n
  rinv : map ∘ rep = id
  min : ∀ (i : Fin n) (v : Fin size.val), map i = v → rep v ≤ i
  mono : ∀ (u v : Fin size.val), u < v → rep u < rep v

namespace Partition

section

variable {n : ℕ} (p : Partition n) (i j : Fin n)

/-- The equivalence relation generated by a partition. -/
@[inline]
abbrev mapEq : Prop :=
  p.map i = p.map j

/-- The proposition that the image of the first argument is less than the image of the second. -/
@[inline]
abbrev mapLT : Prop :=
  p.map i < p.map j

/-- The proposition that the image of the first argument is less than the image of the second. -/
@[inline]
abbrev mapGT : Prop :=
  p.map j < p.map i

/-- Function for splitting on the ordering of the images of two inputs. -/
protected def splitOn {α : Sort*} : (p.mapEq i j → α) → (p.mapLT i j → α) → (p.mapGT i j → α) → α :=
  fun h₁ h₂ h₃ ↦
  if heq : p.mapEq i j then h₁ heq else
  if hlt : p.mapLT i j then h₂ hlt else
  h₃ (Fin.lt_iff_le_and_ne.mpr ⟨Fin.not_lt.mp hlt, Ne.symm heq⟩)

theorem splitOn_eq {α : Sort*} {h₁ : p.mapEq i j → α} {h₂ : p.mapLT i j → α} {h₃ : p.mapGT i j → α}
    (h : p.mapEq i j) : p.splitOn i j h₁ h₂ h₃ = h₁ h :=
  dite_cond_eq_true (eq_true_intro h)

theorem splitOn_lt {α : Sort*} {h₁ : p.mapEq i j → α} {h₂ : p.mapLT i j → α} {h₃ : p.mapGT i j → α}
    (h : p.mapLT i j) : p.splitOn i j h₁ h₂ h₃ = h₂ h :=
  (dite_cond_eq_false (eq_false_intro (Fin.ne_of_lt h))).trans <|
    dite_cond_eq_true (eq_true_intro h)

theorem splitOn_gt {α : Sort*} {h₁ : p.mapEq i j → α} {h₂ : p.mapLT i j → α} {h₃ : p.mapGT i j → α}
    (h : p.mapGT i j) : p.splitOn i j h₁ h₂ h₃ = h₃ h :=
  (dite_cond_eq_false (eq_false_intro (Fin.ne_of_gt h))).trans <|
    dite_cond_eq_false (eq_false_intro (Fin.not_lt.mpr (Fin.le_of_lt h)))

instance mapEq_decidable : Decidable (p.mapEq i j) :=
  by infer_instance

instance mapEq_equivalence : Equivalence p.mapEq :=
  ⟨fun _ ↦ rfl, Eq.symm, Eq.trans⟩

end

section

@[reducible]
def partial_mono_prop {n s : ℕ} (rep : Fin s → Fin n) (m : ℕ) (u : Fin s) : Prop :=
  m ≤ u.val ∧ ∀ v : Fin s, m ≤ v.val → v ≠ u → rep u < rep v

def partial_mono_least_option {n s : ℕ} (rep : Fin s → Fin n) (m : ℕ) : Option (Fin s) :=
  Fin.find (partial_mono_prop rep m)

theorem partial_mono_prop_witnessed_of_inj_of_lt {n s : ℕ} (rep : Fin s → Fin n)
    (inj : Function.Injective rep) (m : ℕ) : m < s → ∃ u : Fin s, partial_mono_prop rep m u := by
  intro h'
  replace h : m ≤ s - 1 := Nat.le_pred_of_lt h'
  induction h using Nat.decreasingInduction with
  | of_succ k hk ih =>
    apply (ih (Nat.succ_lt_of_lt_pred hk)).elim
    intro u ⟨h₁, h₂⟩
    let v : Fin s := ⟨k, hk.trans_le (Nat.pred_le _)⟩
    if h₃ : rep v < rep u then
      apply Exists.intro v
      apply And.intro (Nat.le_refl _)
      intro w hw hn
      if h₄ : w = u then exact h₃.trans_eq (congr_arg _ h₄.symm) else
      apply h₃.trans
      replace hw : k < w.val := Nat.lt_of_le_of_ne hw (Fin.val_ne_of_ne hn.symm)
      exact h₂ _ (Nat.succ_le_of_lt (hw)) h₄
    else
      apply Exists.intro u
      apply And.intro ((Nat.le_succ _).trans h₁)
      intro w hw hn
      apply (Nat.lt_or_eq_of_le hw).elim (fun h₄ ↦ h₂ w (Nat.succ_le_of_lt h₄) hn)
      intro he
      obtain rfl : w = v := Fin.eq_of_val_eq he.symm
      apply Nat.lt_of_le_of_ne (Nat.le_of_not_lt h₃)
      intro h₄
      apply hn.symm
      exact inj (Fin.eq_of_val_eq h₄)
  | self =>
    apply Exists.intro ⟨_, h'⟩
    apply And.intro (Nat.le_refl _)
    intro v hv hn
    obtain rfl : v = ⟨_, h'⟩ := Fin.eq_of_val_eq <| Nat.le_antisymm (Nat.le_pred_of_lt v.isLt) hv
    exact False.elim <| hn <| rfl

theorem partial_mono_least_isSome_of_inj_of_lt {n s : ℕ} (rep : Fin s → Fin n)
    (inj : Function.Injective rep) (m : ℕ) (h : m < s) :
    (partial_mono_least_option rep m).isSome := by
  apply Option.isSome_iff_ne_none.mpr
  apply Fin.find_eq_none_iff.not.mpr
  apply not_forall_of_exists_not
  apply (exists_congr (fun _ ↦ not_not)).mpr
  exact partial_mono_prop_witnessed_of_inj_of_lt rep inj m h

def partial_mono_least {n s : ℕ} (rep : Fin s → Fin n) (inj : Function.Injective rep) (m : ℕ)
    (h : m < s) : Fin s :=
  Option.get _ (partial_mono_least_isSome_of_inj_of_lt rep inj m h)

theorem partial_mono_least_ge {n s : ℕ} (rep : Fin s → Fin n) (inj : Function.Injective rep) (m : ℕ)
    (h : m < s) : m ≤ (partial_mono_least rep inj m h).val :=
  have he := Option.eq_some_of_isSome (partial_mono_least_isSome_of_inj_of_lt rep inj m h)
  (Fin.find_eq_some_iff.mp he).left.left

theorem partial_mono_least_partial_mono {n s : ℕ} (rep : Fin s → Fin n)
    (inj : Function.Injective rep) (m : ℕ) (h : m < s) :
    ∀ v : Fin s, m ≤ v.val → v ≠ (partial_mono_least rep inj m h) →
    rep (partial_mono_least rep inj m h) < rep v :=
  have he := Option.eq_some_of_isSome (partial_mono_least_isSome_of_inj_of_lt rep inj m h)
  (Fin.find_eq_some_iff.mp he).left.right

theorem rep_inj_of_rinv {n s : ℕ} {map : Fin n → Fin s} {rep : Fin s → Fin n}
    (rinv : map ∘ rep = id) : Function.Injective rep :=
  match s with
  | 0 => fun i ↦ i.elim0
  | _ + 1 => Function.injective_iff_hasLeftInverse.mpr <| Exists.intro map (congr_fun rinv)

def partial_mono_map {n s : ℕ} (map : Fin n → Fin s) (rep : Fin s → Fin n) (rinv : map ∘ rep = id)
    (m : ℕ) (h : m < s) : Fin n → Fin s := fun i ↦
  let v : Fin s := map i
  if v.val = m then partial_mono_least rep (rep_inj_of_rinv rinv) m h else
  if v = partial_mono_least rep (rep_inj_of_rinv rinv) m h then ⟨m, h⟩ else v

theorem partial_mono_map_eq_iff_map_eq {n s : ℕ} (map : Fin n → Fin s) (rep : Fin s → Fin n)
    (rinv : map ∘ rep = id) (m : ℕ) (h : m < s) : ∀ i j : Fin n,
    partial_mono_map map rep rinv m h i = partial_mono_map map rep rinv m h j ↔ map i = map j := by
  intro i j
  let u := map i
  let v := map j
  if h₁ : u.val = m then
    rw [partial_mono_map, ite_cond_eq_true _ _ (eq_true_intro h₁)]
    if h₂ : v.val = m then
      rw [partial_mono_map, ite_cond_eq_true _ _ (eq_true_intro h₂)]
      simp
      exact Fin.eq_of_val_eq <| h₁.trans h₂.symm
    else
      rw [partial_mono_map, ite_cond_eq_false _ _ (eq_false_intro h₂)]
      if h₃ : v = partial_mono_least rep (rep_inj_of_rinv rinv) m h then
        rw [ite_cond_eq_true _ _ (eq_true_intro h₃)]
        replace h₂ := @Fin.ne_of_val_ne _ _ ⟨m, h⟩ h₂
        simp [h₃.symm.trans_ne h₂]
        exact (@Fin.eq_of_val_eq _ _ ⟨m, h⟩ h₁).trans_ne h₂.symm
      else
        rw [ite_cond_eq_false _ _ (eq_false_intro h₃)]
        unfold v at h₃
        rw [eq_false_intro (Ne.symm h₃)]
        simp
        apply Fin.ne_of_val_ne
        exact h₁.trans_ne <| Ne.symm h₂
  else
    rw [partial_mono_map, ite_cond_eq_false _ _ (eq_false_intro h₁)]
    if h₂ : u = partial_mono_least rep (rep_inj_of_rinv rinv) m h then
      rw [ite_cond_eq_true _ _ (eq_true_intro h₂)]
      if h₃ : v.val = m then
        rw [partial_mono_map, ite_cond_eq_true _ _ (eq_true_intro h₃)]
        simp [(h₂.symm.trans_ne (@Fin.ne_of_val_ne _ _ ⟨m, h⟩ h₁)).symm]
        apply Fin.ne_of_val_ne
        exact Ne.symm <| h₃.trans_ne (Ne.symm h₁)
      else
        rw [partial_mono_map, ite_cond_eq_false _ _ (eq_false_intro h₃)]
        if h₄ : v = partial_mono_least rep (rep_inj_of_rinv rinv) m h then
          rw [ite_cond_eq_true _ _ (eq_true_intro h₄)]
          simp
          exact h₂.trans h₄.symm
        else
          rw [ite_cond_eq_false _ _ (eq_false_intro h₄)]
          rw [eq_false_intro (@Fin.ne_of_val_ne _ ⟨m, h⟩ _ (Ne.symm h₃))]
          simp
          exact h₂.trans_ne <| Ne.symm h₄
    else
      rw [ite_cond_eq_false _ _ (eq_false_intro h₂)]
      if h₃ : v.val = m then
        rw [partial_mono_map, ite_cond_eq_true _ _ (eq_true_intro h₃)]
        rw [eq_false_intro h₂]
        simp
        apply Fin.ne_of_val_ne
        exact Ne.symm <| h₃.trans_ne <| Ne.symm h₁
      else
        rw [partial_mono_map, ite_cond_eq_false _ _ (eq_false_intro h₃)]
        if h₄ : v = partial_mono_least rep (rep_inj_of_rinv rinv) m h then
          rw [ite_cond_eq_true _ _ (eq_true_intro h₄)]
          rw [eq_false_intro (@Fin.ne_of_val_ne _ _ ⟨m, h⟩ h₁)]
          simp
          exact Ne.symm <| h₄.trans_ne <| Ne.symm h₂
        else
          rw [ite_cond_eq_false _ _ (eq_false_intro h₄)]

def partial_mono_rep {n s : ℕ} (rep : Fin s → Fin n) (inj : Function.Injective rep) (m : ℕ)
    (h : m < s) : Fin s → Fin n := fun v ↦
  if v.val = m then rep (partial_mono_least rep inj m h) else
  if v = partial_mono_least rep inj m h then rep ⟨m, h⟩ else rep v

theorem partial_mono_rinv {n s : ℕ} (map : Fin n → Fin s) (rep : Fin s → Fin n)
    (rinv : map ∘ rep = id) (m : ℕ) (h : m < s) :
    partial_mono_map map rep rinv m h ∘ partial_mono_rep rep (rep_inj_of_rinv rinv) m h = id := by
  funext v
  simp
  if h₁ : v.val = m then
    rw [partial_mono_rep, ite_cond_eq_true _ _ (eq_true_intro h₁)]
    have h₂ := congr_fun rinv (partial_mono_least rep (rep_inj_of_rinv rinv) m h)
    simp at h₂
    rw [partial_mono_map]
    simp [h₂]
    if h₃ : partial_mono_least rep (rep_inj_of_rinv rinv) m h = ⟨m, h⟩ then
      simp [h₃]
      exact Fin.eq_of_val_eq h₁.symm
    else
      simp [Fin.val_ne_of_ne h₃]
      exact Fin.eq_of_val_eq h₁.symm
  else
    rw [partial_mono_rep, ite_cond_eq_false _ _ (eq_false_intro h₁)]
    if h₂ : v = partial_mono_least rep (rep_inj_of_rinv rinv) m h then
      rw [ite_cond_eq_true _ _ (eq_true_intro h₂), partial_mono_map]
      have h₃ := congr_fun rinv ⟨m, h⟩
      simp at h₃
      simp [h₃]
      exact h₂.symm
    else
      rw [ite_cond_eq_false _ _ (eq_false_intro h₂), partial_mono_map]
      have h₃ := congr_fun rinv v
      simp at h₃
      simp [h₃, h₁, h₂]

theorem partial_mono_rep_min_of_rep_min {n s : ℕ} (map : Fin n → Fin s) (rep : Fin s → Fin n)
    (rinv : map ∘ rep = id) (m : ℕ) (h : m < s) :
    (∀ (i : Fin n) (v : Fin s), map i = v → rep v ≤ i) → ∀ (i : Fin n) (v : Fin s),
    partial_mono_map map rep rinv m h i = v →
    partial_mono_rep rep (rep_inj_of_rinv rinv) m h v ≤ i := by
  intro min i v he
  if h₁ : v.val = m then
    rw [partial_mono_rep, ite_cond_eq_true _ _ (eq_true_intro h₁)]
    apply min
    if h₂ : (map i).val = m then
      rw [partial_mono_map, ite_cond_eq_true _ _ (eq_true_intro h₂)] at he
      apply Fin.eq_of_val_eq
      exact h₂.trans <| h₁.symm.trans <| Fin.val_eq_of_eq he.symm
    else
      rw [partial_mono_map, ite_cond_eq_false _ _ (eq_false_intro h₂)] at he
      if h₃ : map i = partial_mono_least rep (rep_inj_of_rinv rinv) m h then
        exact h₃
      else
        rw [ite_cond_eq_false _ _ (eq_false_intro h₃)] at he
        exact False.elim <| h₂ <| (Fin.val_eq_of_eq he).trans h₁
  else
    rw [partial_mono_rep, ite_cond_eq_false _ _ (eq_false_intro h₁)]
    if h₂ : v = partial_mono_least rep (rep_inj_of_rinv rinv) m h then
      rw [ite_cond_eq_true _ _ (eq_true_intro h₂)]
      apply min
      if h₃ : (map i).val = m then
        rw [partial_mono_map, ite_cond_eq_true _ _ (eq_true_intro h₃)] at he
        exact Fin.eq_of_val_eq h₃
      else
        rw [partial_mono_map, ite_cond_eq_false _ _ (eq_false_intro h₃)] at he
        if h₄ : map i = partial_mono_least rep (rep_inj_of_rinv rinv) m h then
          rw [ite_cond_eq_true _ _ (eq_true_intro h₄)] at he
          exact h₄.trans <| h₂.symm.trans <| he.symm
        else
          rw [ite_cond_eq_false _ _ (eq_false_intro h₄)] at he
          exact False.elim <| h₄ <| he.trans h₂
      else
        rw [ite_cond_eq_false _ _ (eq_false_intro h₂)]
        apply min
        if h₃ : (map i).val = m then
          rw [partial_mono_map, ite_cond_eq_true _ _ (eq_true_intro h₃)] at he
          exact False.elim <| h₂ <| he.symm
        else
          rw [partial_mono_map, ite_cond_eq_false _ _ (eq_false_intro h₃)] at he
          if h₄ : map i = partial_mono_least rep (rep_inj_of_rinv rinv) m h then
            rw [ite_cond_eq_true _ _ (eq_true_intro h₄)] at he
            exact False.elim <| h₁ <| Fin.val_eq_of_eq he.symm
          else
            rw [ite_cond_eq_false _ _ (eq_false_intro h₄)] at he
            exact he

theorem partial_mono_rep_relaxes_partial_mono {n s : ℕ} (rep : Fin s → Fin n)
    (inj : Function.Injective rep) (m : ℕ) (h : m < s) :
    (∀ u : Fin s, u.val < m → ∀ v : Fin s, u < v → rep u < rep v) →
    ∀ u : Fin s, u.val < m + 1 → ∀ v : Fin s, u < v →
    partial_mono_rep rep inj m h u < partial_mono_rep rep inj m h v := by
  intro mono u hu v hv
  apply (Nat.lt_or_eq_of_le (Nat.le_of_lt_succ hu)).elim
  · intro h₁
    specialize mono _ h₁
    have h₂ : u.val ≠ m := Nat.ne_of_lt h₁
    have h₃ : u ≠ partial_mono_least rep inj m h :=
      Fin.ne_of_val_ne <| Nat.ne_of_lt <| h₁.trans_le <| partial_mono_least_ge rep inj m h
    rw [partial_mono_rep]
    simp [h₂, h₃]
    if h₄ : v.val = m then
      simp [partial_mono_rep, h₄]
      exact mono _ <| h₁.trans_le <| partial_mono_least_ge rep inj m h
    else
      if h₅ : v = partial_mono_least rep inj m h then
        simp [partial_mono_rep, h₄, eq_true_intro h₅]
        exact mono _ h₁
      else
        simp [partial_mono_rep, h₄, h₅]
        exact mono _ hv
  · intro h₁
    rw [partial_mono_rep]
    simp [h₁]
    have h₄ : v.val ≠ m := Nat.ne_of_lt' <| h₁.symm.le.trans_lt hv
    have hyp := partial_mono_least_partial_mono rep inj m h
    if h₅ : v = partial_mono_least rep inj m h then
      simp [partial_mono_rep, h₄, eq_true_intro h₅]
      apply partial_mono_least_partial_mono rep inj m h _ (Nat.le_refl _)
      apply Fin.ne_of_val_ne
      exact ((Fin.val_eq_of_eq h₅.symm).trans_ne h₄).symm
    else
      simp [partial_mono_rep, h₄, h₅]
      exact partial_mono_least_partial_mono rep inj m h _ (h₁.symm.le.trans hv.le) h₅

def partial_mono_map_rep_rinv_rec {n s : ℕ} (map : Fin n → Fin s) (rep : Fin s → Fin n)
    (rinv : map ∘ rep = id) (m : ℕ) (h : m ≤ s) :
    (m : Fin n → Fin s) × (r : Fin s → Fin n) × PLift (m ∘ r = id) :=
  match m with
  | 0 => ⟨map, rep, ⟨rinv⟩⟩
  | m + 1 =>
    let ⟨_, _, ⟨rinv'⟩⟩ := partial_mono_map_rep_rinv_rec map rep rinv m ((Nat.le_succ _).trans h)
    ⟨partial_mono_map _ _ rinv' m (Nat.lt_of_succ_le h),
    partial_mono_rep _ (rep_inj_of_rinv rinv') m _, ⟨partial_mono_rinv _ _ _ _ _⟩⟩

theorem partial_mono_map_rec_eq_iff_map_eq {n s : ℕ} (map : Fin n → Fin s) (rep : Fin s → Fin n)
    (rinv : map ∘ rep = id) (m : ℕ) (h : m ≤ s) : ∀ i j : Fin n,
    (partial_mono_map_rep_rinv_rec map rep rinv m h).fst i
    = (partial_mono_map_rep_rinv_rec map rep rinv m h).fst j ↔ map i = map j := by
  induction m with
  | zero =>
    intro i j
    simp [partial_mono_map_rep_rinv_rec]
  | succ m ih =>
    intro i j
    apply (partial_mono_map_eq_iff_map_eq _ _ (partial_mono_map_rep_rinv_rec map rep rinv m
      ((Nat.le_succ _).trans h)).snd.snd.down m h i j).trans
    exact ih ((Nat.le_succ _).trans h) _ _

theorem partial_mono_rep_rec_min_of_rep_min {n s : ℕ} (map : Fin n → Fin s) (rep : Fin s → Fin n)
    (rinv : map ∘ rep = id) (m : ℕ) (h : m ≤ s) :
    (∀ (i : Fin n) (v : Fin s), map i = v → rep v ≤ i) → ∀ (i : Fin n) (v : Fin s),
    (partial_mono_map_rep_rinv_rec map rep rinv m h).fst i = v →
    (partial_mono_map_rep_rinv_rec map rep rinv m h).snd.fst v ≤ i := by
  induction m with
  | zero => exact (·)
  | succ m ih =>
    intro min
    apply partial_mono_rep_min_of_rep_min _ _ (partial_mono_map_rep_rinv_rec map rep rinv m
      ((Nat.le_succ _).trans h)).snd.snd.down m (Nat.lt_of_succ_le h)
    exact ih ((Nat.le_succ _).trans h) min

theorem partial_mono_rep_rec_partial_mono {n s : ℕ} (map : Fin n → Fin s) (rep : Fin s → Fin n)
    (rinv : map ∘ rep = id) (m : ℕ) (h : m ≤ s) : ∀ u : Fin s, u.val < m → ∀ v : Fin s, u < v →
    (partial_mono_map_rep_rinv_rec map rep rinv m h).snd.fst u <
    (partial_mono_map_rep_rinv_rec map rep rinv m h).snd.fst v := by
  induction m with
  | zero =>
    intro _ hu
    exact False.elim <| Nat.not_lt_zero _ hu
  | succ m ih =>
    apply partial_mono_rep_relaxes_partial_mono _ _ m (Nat.lt_of_succ_le h)
    exact ih ((Nat.le_succ _).trans h)

def monotone_map {n s : ℕ} (map : Fin n → Fin s) (rep : Fin s → Fin n) (rinv : map ∘ rep = id) :
    Fin n → Fin s :=
  (partial_mono_map_rep_rinv_rec map rep rinv s (Nat.le_refl _)).fst

theorem monotone_map_eq_iff_eq {n s : ℕ} (map : Fin n → Fin s) (rep : Fin s → Fin n)
    (rinv : map ∘ rep = id) : ∀ i j : Fin n,
    monotone_map map rep rinv i = monotone_map map rep rinv j ↔ map i = map j :=
  partial_mono_map_rec_eq_iff_map_eq map rep rinv s (Nat.le_refl _)

def monotone_rep {n s : ℕ} (map : Fin n → Fin s) (rep : Fin s → Fin n) (rinv : map ∘ rep = id) :
    Fin s → Fin n :=
  (partial_mono_map_rep_rinv_rec map rep rinv s (Nat.le_refl _)).snd.fst

theorem monotone_rinv {n s : ℕ} (map : Fin n → Fin s) (rep : Fin s → Fin n)
    (rinv : map ∘ rep = id) : monotone_map map rep rinv ∘ monotone_rep map rep rinv = id :=
  (partial_mono_map_rep_rinv_rec map rep rinv s (Nat.le_refl _)).snd.snd.down

theorem monotone_min {n s : ℕ} (map : Fin n → Fin s) (rep : Fin s → Fin n) (rinv : map ∘ rep = id) :
    (∀ (i : Fin n) (v : Fin s), map i = v → rep v ≤ i) → ∀ (i : Fin n) (v : Fin s),
    monotone_map map rep rinv i = v → monotone_rep map rep rinv v ≤ i :=
  partial_mono_rep_rec_min_of_rep_min map rep rinv s (Nat.le_refl _)

theorem monotone_mono {n s : ℕ} (map : Fin n → Fin s) (rep : Fin s → Fin n)
    (rinv : map ∘ rep = id) : ∀ (u v : Fin s), u < v →
    monotone_rep map rep rinv u < monotone_rep map rep rinv v :=
  fun u ↦ partial_mono_rep_rec_partial_mono map rep rinv s (Nat.le_refl s) u (Fin.isLt _)

end

section

variable {n s : ℕ} (map : Fin n → Fin s)

def minimum_option (v : Fin s) : Option (Fin n) :=
  Fin.find (map · = v)

theorem minimum_option_isSome_of_surj (surj : Function.Surjective map) (v : Fin s) :
    (minimum_option map v).isSome := by
  apply Option.isSome_iff_ne_none.mpr
  apply Fin.find_eq_none_iff.not.mpr
  apply not_forall_of_exists_not
  apply (exists_congr (fun _ ↦ not_not)).mpr
  exact surj v

variable (surj : Function.Surjective map)

def minimum_rep (v : Fin s) : Fin n :=
  Option.get _ (minimum_option_isSome_of_surj map surj v)

theorem minimum_rinv : map ∘ minimum_rep map surj = id :=
  funext <| fun v ↦ (Fin.find_eq_some_iff.mp (Option.eq_some_of_isSome
    (minimum_option_isSome_of_surj map surj v))).left

theorem minimum_min : ∀ (i : Fin n) (v : Fin s), map i = v → minimum_rep map surj v ≤ i :=
  fun i v ↦ (Fin.find_eq_some_iff.mp
    (Option.eq_some_of_isSome (minimum_option_isSome_of_surj map surj v))).right i

def of_surjective : Partition n where
  size := ⟨s, Nat.lt_succ_of_le (ge_of_surj _ surj)⟩
  map := monotone_map map (minimum_rep map surj) (minimum_rinv map surj)
  rep := monotone_rep map (minimum_rep map surj) (minimum_rinv map surj)
  rinv := monotone_rinv map (minimum_rep map surj) (minimum_rinv map surj)
  min := monotone_min map (minimum_rep map surj) (minimum_rinv map surj) (minimum_min map surj)
  mono := monotone_mono map (minimum_rep map surj) (minimum_rinv map surj)

theorem of_surjective_iff_map : ∀ i j : Fin n, (of_surjective map surj).mapEq i j ↔ map i = map j :=
  monotone_map_eq_iff_eq map (minimum_rep map surj) (minimum_rinv map surj)

end

section

variable {n : ℕ} (p : Partition n)

@[simp]
theorem map_rep_id (v : Fin p.size.val) : p.map (p.rep v) = v :=
  congr_fun p.rinv v

theorem map_surj : Function.Surjective p.map :=
  Function.RightInverse.surjective p.map_rep_id

theorem rep_inj : Function.Injective p.rep :=
  Function.LeftInverse.injective p.map_rep_id

theorem eq_rep_of_min (i : Fin n) (v : Fin p.size.val) :
    p.map i = v → (∀ j : Fin n, p.map j = v → i ≤ j) → i = p.rep v :=
  fun h₁ h₂ ↦ Fin.eq_of_val_eq <| Nat.le_antisymm (h₂ _ (p.map_rep_id v)) <| p.min _ _ h₁

theorem le_rep (v : Fin p.size.val) : v.val ≤ (p.rep v).val := by
  cases v with
  | mk v hi =>
    induction v with
    | zero => exact Nat.zero_le _
    | succ v ih =>
      apply Nat.succ_le_of_lt
      apply Nat.lt_of_le_of_lt (ih ((Nat.lt_succ_self _).trans hi))
      exact p.mono _ _ (Nat.lt_succ_self _)

theorem map_le (i : Fin n) : (p.map i).val ≤ i.val := by
  apply Nat.le_of_not_lt
  intro h₁
  let j : Fin p.size.val := ⟨i.val, h₁.trans (p.map i).isLt⟩
  exact Nat.not_le_of_lt (Nat.lt_of_lt_of_le (p.mono j _ h₁) (p.min _ _ rfl)) (p.le_rep j)

theorem rep_map_id_iff_min (i : Fin n) :
    p.rep (p.map i) = i ↔ ∀ j : Fin n, p.map j = p.map i → i ≤ j :=
  ⟨fun h _ he ↦ h.symm.le.trans (p.min _ _ he), (Eq.symm <| eq_rep_of_min _ _ _ rfl ·)⟩

theorem lt_iff_rep_lt_rep {u v : Fin p.size.val} : u < v ↔ p.rep u < p.rep v := by
  apply Iff.intro (p.mono _ _)
  intro h
  apply Nat.lt_of_not_le
  intro h₁
  apply (Nat.lt_or_eq_of_le h₁).elim
  · intro h₂
    apply Nat.not_lt_of_gt h
    exact p.mono _ _ h₂
  · intro h₂
    apply Nat.not_le_of_lt h
    apply Nat.le_of_eq
    apply Fin.val_eq_of_eq
    exact congr_arg _ (Fin.eq_of_val_eq h₂)

theorem le_iff_rep_le_rep {u v : Fin p.size.val} : u ≤ v ↔ p.rep u ≤ p.rep v := by
  constructor
  · intro h
    apply (Nat.lt_or_eq_of_le h).elim
    · intro h
      exact (p.mono _ _ h).le
    · intro h
      apply Nat.le_of_eq
      apply Fin.val_eq_of_eq
      exact congr_arg _ (Fin.eq_of_val_eq h)
  · intro h
    apply (Nat.lt_or_eq_of_le h).elim
    · intro h
      apply Nat.le_of_lt
      exact p.lt_iff_rep_lt_rep.mpr h
    · intro h
      apply Nat.le_of_eq
      apply Fin.val_eq_of_eq
      apply p.rep_inj
      exact Fin.eq_of_val_eq h

theorem map_zero_eq_zero {i : Fin n} (h : i.val = 0) :
    p.map i = ⟨0, Nat.zero_lt_of_lt (p.map i).isLt⟩ :=
  Fin.eq_of_val_eq <| Nat.eq_zero_of_le_zero <| (p.map_le _).trans_eq h

theorem rep_zero_eq_zero {v : Fin p.size.val} (h : v.val = 0) :
    p.rep v = ⟨0, (h.symm.le.trans_lt v.isLt).trans_le (Nat.le_of_lt_succ p.size.isLt)⟩ :=
  Eq.symm <| p.eq_rep_of_min _ _ ((p.map_zero_eq_zero rfl).trans <| Fin.eq_of_val_eq h.symm) <|
    fun _ _ ↦ Nat.zero_le _

theorem lt_zero_of_lt_rep {v : Fin p.size.val} {i : Fin n} (h : i < p.rep v) : 0 < v.val :=
  Nat.lt_of_not_le <| fun hn ↦ Nat.not_lt_zero _
    (h.trans_eq (p.rep_zero_eq_zero (Nat.eq_zero_of_le_zero hn)))

theorem eq_zero_iff_rep_eq_zero (v : Fin p.size.val) : v.val = 0 ↔ (p.rep v).val = 0 :=
  ⟨fun h ↦ (Fin.val_eq_of_eq <| p.rep_zero_eq_zero h).trans (Fin.val_mk _),
    (Nat.eq_zero_of_le_zero <| (p.le_rep v).trans_eq ·)⟩

theorem rep_lt_of_rep_succ_le (v : ℕ) (h : v + 1 < p.size.val) (i : Fin n) :
    p.rep ⟨v + 1, h⟩ ≤ i → p.rep ⟨v, (Nat.lt_succ_self _).trans h⟩ < i :=
  (p.mono _ _ (Nat.lt_succ_self v)).trans_le

theorem rep_succ_le_rep_iff_rep_lt_rep (u : ℕ) (h : u + 1 < p.size.val) (v : Fin p.size.val) :
    p.rep ⟨u + 1, h⟩ ≤ p.rep v ↔ p.rep ⟨u, (Nat.lt_succ_self _).trans h⟩ < p.rep v :=
  p.le_iff_rep_le_rep.symm.trans <| Nat.succ_le_iff.trans <|
    @p.lt_iff_rep_lt_rep _ ⟨u, (Nat.lt_succ_self _).trans h⟩ v

theorem rep_succ_le_of_rep_lt_of_rep_map_id (v : ℕ) (h : v + 1 < p.size.val) (i : Fin n) :
    p.rep ⟨v, (Nat.lt_succ_self _).trans h⟩ < i → p.rep (p.map i) = i → p.rep ⟨v + 1, h⟩ ≤ i := by
  intro h₁ h₂
  rw [<-h₂]
  apply (p.rep_succ_le_rep_iff_rep_lt_rep v h (p.map i)).mpr
  exact h₁.trans_eq h₂.symm

theorem le_rep_of_lt_rep_succ_of_rep_map_id (v : ℕ) (h : v + 1 < p.size.val) (i : Fin n) :
    i < (p.rep ⟨v + 1, h⟩).val → p.rep (p.map i) = i →
    i ≤ p.rep ⟨v, (Nat.lt_succ_self _).trans h⟩ := by
  intro h₁ h₂
  apply Nat.le_of_not_lt
  intro h₃
  apply Nat.not_le_of_lt ((p.rep_succ_le_of_rep_lt_of_rep_map_id v h i h₃ h₂).trans_lt h₁)
  exact Nat.le_refl _

end

section

variable {n : ℕ} (p p' : Partition n)

theorem rep_eq_of_map_eq : (∀ i : Fin n, (p.map i).val = (p'.map i).val) →
    ∀ (v : Fin p.size.val) (v' : Fin p'.size.val), v.val = v'.val → p.rep v = p'.rep v' :=
  fun h _ _ hv ↦ p'.eq_rep_of_min _ _
    (Fin.eq_of_val_eq <| (h _).symm.trans <| (Fin.val_eq_of_eq (p.map_rep_id _)).trans hv) <|
    fun _ hi ↦ p.min _ _ <| Fin.eq_of_val_eq <| (h _).trans <| (Fin.val_eq_of_eq hi).trans hv.symm

protected theorem map_ext :
    p.size.val = p'.size.val → (∀ i : Fin n, (p.map i).val = (p'.map i).val) → p = p' := by
  intro h₁ h₂
  have h₃ := rep_eq_of_map_eq p p' h₂
  match p, p' with
  | Partition.mk s₁ m₁ r₁ ri₁ min₁ _, Partition.mk s₂ m₂ r₂ ri₂ min₂ _ =>
    obtain rfl : s₁ = s₂ := Fin.eq_of_val_eq h₁
    obtain rfl : m₁ = m₂ := funext <| fun i ↦ Fin.eq_of_val_eq (h₂ i)
    obtain rfl : r₁ = r₂ := funext <| fun i ↦ h₃ i i rfl
    rfl

theorem map'_rep_inj_of_mapEq_bij (h : ∀ i j : Fin n, p.mapEq i j ↔ p'.mapEq i j) :
    Function.Injective (p'.map ∘ p.rep) := by
  intro i j
  simp
  intro he
  replace he := (h (p.rep i) (p.rep j)).mpr he
  unfold mapEq at he
  simp at he
  exact he

theorem map_rep'_inj_of_mapEq_bij (h : ∀ i j : Fin n, p.mapEq i j ↔ p'.mapEq i j) :
    Function.Injective (p.map ∘ p'.rep) := by
  intro i j
  simp
  intro he
  replace he := (h (p'.rep i) (p'.rep j)).mp he
  unfold mapEq at he
  simp at he
  exact he

theorem size_eq_of_mapEq_bij (h : ∀ i j : Fin n, p.mapEq i j ↔ p'.mapEq i j) :
    p.size.val = p'.size.val :=
  Nat.le_antisymm (le_of_inj _ <| map'_rep_inj_of_mapEq_bij _ _ h) <|
    le_of_inj _ <| map_rep'_inj_of_mapEq_bij _ _ h

theorem rep_map_inv_of_mapEq_bij (h : ∀ i j : Fin n, p.mapEq i j ↔ p'.mapEq i j) :
    ∀ (i : Fin n), p.rep (p.map i) = p'.rep (p'.map i) := by
  intro i
  match n with
  | 0 => exact i.elim0
  | n + 1 =>
  induction i with
  | mk i hi =>
  induction i using Nat.strongRec with
  | ind i ih =>
  if h₁ : p.rep (p.map ⟨i, hi⟩) = ⟨i, hi⟩ then
    have h₂ := (p.rep_map_id_iff_min _).mp h₁
    have h₃ : ∀ j, p'.map j = p'.map ⟨i, hi⟩ → i ≤ j.val := (h₂ · <| (h _ _).mpr ·)
    exact h₁.trans ((p'.rep_map_id_iff_min _).mpr h₃).symm
  else
    have h₂ := (p.rep_map_id_iff_min ⟨i, hi⟩).not.mp h₁
    apply (not_forall.mp h₂).elim
    intro j
    simp
    intro h₃ h₄
    rw [<-h₃, <-(h _ _).mp h₃]
    exact ih j.val h₄ (Nat.lt_trans h₄ hi)

theorem rep_comm_inj_of_mapEq (h : ∀ i j : Fin n, p.mapEq i j ↔ p'.mapEq i j) :
    ∀ (v : Fin p.size.val) (v' : Fin p'.size.val), p.rep v = p'.rep v' → v.val = v'.val := by
  intro v
  induction v with
  | mk v h₁ =>
  induction v with
  | zero =>
    simp [rep_zero_eq_zero]
    intro v' h
    exact ((p'.eq_zero_iff_rep_eq_zero v').mpr (Fin.val_eq_of_eq h.symm)).symm
  | succ v ih =>
    intro v' h₂
    apply @Fin.val_eq_of_eq _ ⟨_, h₁.trans_eq (size_eq_of_mapEq_bij _ _ h)⟩
    have h₃ := p.rep_lt_of_rep_succ_le v h₁ _ h₂.le
    have h₄ : 0 < v'.val := p'.lt_zero_of_lt_rep h₃
    let k : Fin p'.size.val := ⟨v'.val - 1, (Nat.pred_le _).trans_lt v'.isLt⟩
    have hk : v' = ⟨k.val + 1, (Nat.sub_add_cancel (Nat.one_le_of_lt h₄)).le.trans_lt v'.isLt⟩ :=
      Fin.eq_of_val_eq <| Eq.symm <| Nat.sub_add_cancel <| Nat.one_le_of_lt h₄
    have h₅ := (Fin.val_eq_of_eq hk.symm).le.trans_lt v'.isLt
    rw [hk] at h₂ h₃
    simp [hk]
    apply ih ((Nat.lt_succ_self _).trans h₁) k
    apply Fin.eq_of_val_eq
    apply Nat.le_antisymm
    · apply p'.le_rep_of_lt_rep_succ_of_rep_map_id _ _ _ h₃
      simp [<-rep_map_inv_of_mapEq_bij _ _ h]
    · apply p.le_rep_of_lt_rep_succ_of_rep_map_id _ _ _ (p'.rep_lt_of_rep_succ_le k h₅ _ h₂.symm.le)
      simp [rep_map_inv_of_mapEq_bij _ _ h]

theorem map_eq_of_mapEq_bij (h : ∀ i j : Fin n, p.mapEq i j ↔ p'.mapEq i j) :
    ∀ i : Fin n, (p.map i).val = (p'.map i).val :=
  fun _ ↦ rep_comm_inj_of_mapEq _ _ h _ _ <| rep_map_inv_of_mapEq_bij _ _ h _

@[ext]
protected theorem ext : (∀ i j : Fin n, p.mapEq i j ↔ p'.mapEq i j) → p = p' :=
  fun h ↦ Partition.map_ext _ _ (size_eq_of_mapEq_bij _ _ h) <| map_eq_of_mapEq_bij _ _ h

end


section

variable {n : ℕ} (p : Partition n) (r : Fin n → Fin n → Prop)

def sound : Prop := ∀ i j : Fin n, p.mapEq i j → r i j

def exact : Prop := ∀ i j : Fin n, r i j → p.mapEq i j

theorem lift_sound (r' : Fin n → Fin n → Prop) : (∀ i j, r i j → r' i j) → p.sound r → p.sound r' :=
  fun hmp hr _ _ he ↦ hmp _ _ (hr _ _ he)

theorem lift_exact (r' : Fin n → Fin n → Prop) : (∀ i j, r i j → r' i j) → p.exact r' → p.exact r :=
  fun hmp hr _ _ he ↦ hr _ _ (hmp _ _ he)

theorem eqvGen_exact_of_exact : p.exact r → p.exact (EqvGen r) := by
  intro h i j hr
  induction hr with
  | rel i j hr => exact h _ _ hr
  | refl i => exact Eq.refl _
  | symm i j h₁ ih => exact ih.symm
  | trans i j k h₁ h₂ ih₁ ih₂ => exact ih₁.trans ih₂

end

section

variable (n : ℕ)

@[reducible]
protected def id (n : ℕ) : Partition n where
  size := last n
  map := (·)
  rep := (·)
  rinv := rfl
  min := fun _ _ h ↦ Fin.le_of_eq h.symm
  mono := fun _ _ ↦ (·)

variable (r : Fin n → Fin n → Prop)

theorem id_eqvGen_sound : (Partition.id n).sound (EqvGen r) := by
  intro i j he
  simp [mapEq] at he
  obtain rfl : i = j := he
  exact EqvGen.refl _

theorem id_weaken_trivial_exact : (Partition.id n).exact (weaken_rel r 0 0) := by
  intro i j ⟨hw, hr⟩
  apply hw.elim
  · intro h
    exact False.elim (Nat.not_lt_zero _ h)
  · intro ⟨_, h⟩
    exact False.elim (Nat.not_lt_zero _ h)

end

section

variable {n : ℕ} (p : Partition n)

def mergeLT_size : Fin (n + 1) :=
  ⟨p.size.val - 1, (Nat.pred_le _).trans_lt p.size.isLt⟩

def mergeLT_fin_of_lt (i : Fin n) {j : Fin n} (h : p.mapLT i j) : Fin p.mergeLT_size.val :=
  ⟨(p.map i).val, Nat.lt_of_lt_of_le h (Nat.le_pred_of_lt (p.map j).isLt)⟩

def mergeLT_fin_of_gt (i : Fin n) {j : Fin n} (h : p.mapGT i j) : Fin p.mergeLT_size.val :=
  ⟨(p.map i).val - 1, Nat.pred_lt_pred (Nat.ne_zero_of_lt h) (p.map i).isLt⟩

variable {l u : Fin n}

def mergeLT_map (h : p.mapLT l u) (i : Fin n) : Fin p.mergeLT_size.val :=
  p.splitOn i u (fun _ ↦ p.mergeLT_fin_of_lt l h) (p.mergeLT_fin_of_lt i) (p.mergeLT_fin_of_gt i)

@[simp]
lemma mergeLT_fin_of_lt_val (i : Fin n) {j : Fin n} (h : p.mapLT i j) :
    (p.mergeLT_fin_of_lt i h).val = (p.map i).val := rfl

@[simp]
lemma mergeLT_fin_of_gt_val (i : Fin n) {j : Fin n} (h : p.mapGT i j) :
    (p.mergeLT_fin_of_gt i h).val = (p.map i).val - 1 := rfl

@[simp]
lemma mergeLT_map_of_eq (h : p.mapLT l u) (i : Fin n) (h' : p.mapEq i u) :
    (p.mergeLT_map h i).val = (p.map l).val :=
  congr_arg _ (p.splitOn_eq _ _ h')

@[simp]
lemma mergeLT_map_of_lt (h : p.mapLT l u) (i : Fin n) (h' : p.mapLT i u) :
    (p.mergeLT_map h i).val = (p.map i).val :=
  congr_arg _ (p.splitOn_lt _ _ h')

@[simp]
lemma mergeLT_map_of_gt (h : p.mapLT l u) (i : Fin n) (h' : p.mapGT i u) :
    (p.mergeLT_map h i).val = (p.map i).val - 1 :=
  congr_arg _ (p.splitOn_gt _ _ h')

lemma mergeLT_map_lt_map_of_gt (h : p.mapLT l u) (i : Fin n) (h' : p.mapGT i u) :
    (p.mergeLT_map h i).val < (p.map i).val :=
  (p.mergeLT_map_of_gt _ _ h').le.trans_lt (Nat.pred_lt_of_lt h')

lemma mergeLT_map_le_map (h : p.mapLT l u) (i : Fin n) :
    (p.mergeLT_map h i).val ≤ (p.map i).val :=
  p.splitOn i u
    (fun h' ↦ (p.mergeLT_map_of_eq _ _ h').le.trans (h.trans_eq h'.symm).le)
    (fun h' ↦ (p.mergeLT_map_of_lt _ _ h').le)
    (fun h' ↦ (p.mergeLT_map_lt_map_of_gt _ _ h').le)

theorem mergeLT_map_eq_lower_iff_eq_or_eq (h : p.mapLT l u) (i : Fin n) :
    (p.mergeLT_map h i).val = (p.map l).val ↔ p.mapEq i l ∨ p.mapEq i u
  := by
    apply p.splitOn i u
    · intro h'
      exact eq_true_intro (p.mergeLT_map_of_eq _ _ h') ▸ (true_iff _).mpr (Or.inr h')
    · intro h'
      rw [p.mergeLT_map_of_lt _ _ h']
      apply Fin.ext_iff.symm.trans
      apply iff_self_or.mpr fun he ↦ False.elim (Fin.ne_of_lt h' he)
    · intro h'
      simp [Fin.ne_of_gt h', Fin.ne_of_gt (Fin.lt_trans h h'), h']
      exact Nat.ne_of_lt' (Nat.lt_of_lt_of_le h (Nat.le_pred_of_lt h'))

theorem mergeLT_map_lt_upper_iff_eq_or_lt (h : p.mapLT l u) (i : Fin n) :
    (p.mergeLT_map h i).val < (p.map u).val ↔ p.mapEq i u ∨ p.mapLT i u
  := by
    apply p.splitOn i u
    · intro h'
      simp [eq_true_intro h']
      exact h
    · intro h'
      simp [p.mergeLT_map_of_lt _ _ h', Fin.ne_of_lt h']
    · intro h'
      simp [p.mergeLT_map_of_gt _ _ h', Fin.ne_of_gt h']
      simp [Fin.not_lt.mpr (Fin.le_of_lt h')]
      apply Nat.le_pred_of_lt h'

theorem mergeLT_map_eq_of_map_eq (h : p.mapLT l u) (i j : Fin n) :
    p.mapEq i j → p.mergeLT_map h i = p.mergeLT_map h j
  := by
    intro h₁
    apply p.splitOn i u
    · intro h₂
      apply Fin.eq_of_val_eq
      apply (p.mergeLT_map_of_eq _ _ h₂).trans
      apply ((p.mergeLT_map_eq_lower_iff_eq_or_eq h j).mpr _).symm
      exact Or.inr (h₁.symm.trans h₂)
    · intro h₂
      apply Fin.eq_of_val_eq
      apply (p.mergeLT_map_of_lt _ _ h₂).trans
      apply (Fin.val_eq_of_eq h₁).trans
      exact (p.mergeLT_map_of_lt _ _ (h₁.symm.trans_lt h₂)).symm
    · intro h₂
      apply Fin.eq_of_val_eq
      apply (p.mergeLT_map_of_gt _ _ h₂).trans
      rw [h₁]
      exact (p.mergeLT_map_of_gt _ _ (h₂.trans_eq h₁)).symm

theorem mergeLT_map_eq_iff (h : p.mapLT l u) (i j : Fin n) :
    p.mergeLT_map h i = p.mergeLT_map h j ↔
    p.mapEq i j ∨ p.mapEq i l ∧ p.mapEq j u ∨ p.mapEq i u ∧ p.mapEq j l
  := by
    apply p.splitOn i u
    · intro h₁
      simp [eq_true_intro h₁, Fin.ne_of_gt (h.trans_eq h₁.symm)]
      apply Fin.ext_iff.trans
      rw [p.mergeLT_map_of_eq _ _ h₁]
      apply Eq.comm.trans
      apply (p.mergeLT_map_eq_lower_iff_eq_or_eq h j).trans
      apply Or.comm.trans
      apply or_congr_left
      constructor
      · intro h₂
        exact h₁.trans h₂.symm
      · intro h₂
        exact h₂.symm.trans h₁
    · intro h₁
      simp [Fin.ne_of_lt h₁]
      apply Fin.ext_iff.trans
      rw [p.mergeLT_map_of_lt _ _ h₁]
      if h₂ : p.mapEq i l then
        rw [Fin.val_eq_of_eq h₂, eq_true_intro h₂]
        apply Eq.comm.trans
        apply (p.mergeLT_map_eq_lower_iff_eq_or_eq h j).trans
        simp
        apply or_congr_left
        constructor
        · intro h₃
          exact h₂.trans h₃.symm
        · intro h₃
          exact h₃.symm.trans h₂
      else
        rw [eq_false_intro h₂]
        simp
        constructor
        · intro h₃
          apply ((p.mergeLT_map_lt_upper_iff_eq_or_lt h j).mp (h₃.symm.trans_lt h₁)).elim
          · intro h₄
            rw [p.mergeLT_map_of_eq _ _ h₄] at h₃
            exact False.elim (h₂ (Fin.eq_of_val_eq h₃))
          · intro h₄
            rw [p.mergeLT_map_of_lt _ _ h₄] at h₃
            exact Fin.eq_of_val_eq h₃
        · intro h₃
          simp [h₃.symm.trans_lt h₁]
          exact Fin.val_eq_of_eq h₃
    · intro h₁
      simp [Fin.ne_of_gt h₁, Fin.ne_of_gt (Fin.lt_trans h h₁)]
      apply Iff.intro _ (p.mergeLT_map_eq_of_map_eq h _ _)
      intro h₂
      replace h₂ := ((p.mergeLT_map_of_gt _ _ h₁)).symm.trans (Fin.val_eq_of_eq h₂)
      have h₃ := Nat.not_lt_of_le ((Nat.le_pred_of_lt h₁).trans_eq h₂)
      have ⟨h₄, h₅⟩ := not_or.mp ((p.mergeLT_map_lt_upper_iff_eq_or_lt h j).not.mp h₃)
      have h₆ := Nat.lt_of_le_of_ne (Nat.le_of_not_lt h₅) (Fin.val_ne_of_ne h₄).symm
      rw [p.mergeLT_map_of_gt _ _ h₆] at h₂
      exact Fin.eq_of_val_eq (Nat.pred_inj (Nat.zero_lt_of_lt h₁) (Nat.zero_lt_of_lt h₆) h₂)

def mergeLT_rep (_ : p.mapLT l u) (i : Fin p.mergeLT_size.val) : Fin n :=
  if i.val < (p.map u).val
  then p.rep (Fin.castLE (Nat.pred_le _) i)
  else p.rep ⟨i.val + 1, Nat.succ_lt_of_lt_pred i.isLt⟩

theorem mergeLT_rinv (h : p.mapLT l u) :
    p.mergeLT_map h ∘ p.mergeLT_rep h = (·) := by
  funext i
  apply Fin.eq_of_val_eq
  if h₁ : i.val < (p.map u).val then
    simp [mergeLT_rep, h₁]
    have h₂ : p.mapLT (p.rep (Fin.castLE (Nat.pred_le _) i)) u := by simp ; exact h₁
    simp [p.mergeLT_map_of_lt _ _ h₂]
  else
    simp [mergeLT_rep, h₁]
    have h₂ : p.mapGT (p.rep ⟨i.val + 1, Nat.succ_lt_of_lt_pred i.isLt⟩) u :=
      by simp ; exact Nat.lt_succ_of_le (Nat.le_of_not_lt h₁)
    simp [p.mergeLT_map_of_gt _ _ h₂]

theorem mergeLT_min (h : p.mapLT l u) (i : Fin n) (j : Fin p.mergeLT_size.val) :
    p.mergeLT_map h i = j → p.mergeLT_rep h j ≤ i
  := by
    intro h₁
    replace h₁ := Fin.val_eq_of_eq h₁
    if h₂ : j.val < (p.map u).val then
      simp [mergeLT_rep, h₂]
      apply p.splitOn i u
      · intro h₃
        exact Nat.le_trans (p.mono _ _ h₂).le (p.min i (p.map u) h₃)
      · intro h₃
        apply p.min
        apply Fin.eq_of_val_eq
        simp [p.mergeLT_map_of_lt _ _ h₃] at h₁
        exact h₁
      · intro h₃
        simp [p.mergeLT_map_of_gt _ _ h₃] at h₁
        apply Fin.le_trans
          (Fin.le_of_lt (p.mono (Fin.castLE (Nat.pred_le _) j) (p.map i) (h₂.trans h₃)))
        exact p.min _ _ rfl
    else
      simp [mergeLT_rep, h₂]
      apply p.splitOn i u
      · intro h₃
        simp [mergeLT_map, p.splitOn_eq _ _ h₃] at h₁
        exact False.elim (h₂ (h₁.symm.le.trans_lt h))
      · intro h₃
        simp [mergeLT_map, p.splitOn_lt _ _ h₃] at h₁
        exact False.elim (h₂ (h₁.symm.le.trans_lt h₃))
      · intro h₃
        simp [p.mergeLT_map_of_gt _ _ h₃] at h₁
        apply p.min
        apply Fin.eq_of_val_eq
        simp [<-h₁]
        exact (Nat.succ_pred (Nat.ne_zero_of_lt h₃)).symm

theorem mergeLT_mono (h : p.mapLT l u) (i j : Fin p.mergeLT_size.val) :
    i < j → p.mergeLT_rep h i < p.mergeLT_rep h j
  := by
    intro h₁
    if h₂ : j.val < (p.map u).val then
      simp [mergeLT_rep, Nat.lt_trans h₁ h₂, h₂]
      exact p.mono _ _ h₁
    else
      if h₃ : i.val < (p.map u).val then
        simp [mergeLT_rep, h₂, h₃]
        apply p.mono
        exact Nat.lt_trans h₁ (Nat.lt_succ_self _)
      else
        simp [mergeLT_rep, h₂, h₃]
        exact p.mono _ _ (Nat.add_lt_add_right h₁ _)

def mergeLT (h : p.mapLT l u) : Partition n where
  size := p.mergeLT_size
  map := p.mergeLT_map h
  rep := p.mergeLT_rep h
  rinv := p.mergeLT_rinv h
  min := p.mergeLT_min h
  mono := p.mergeLT_mono h

theorem mergeLT_mapEq_iff (h : p.mapLT l u) (i j : Fin n) :
    (p.mergeLT h).mapEq i j ↔ p.mapEq i j ∨ p.mapEq i l ∧ p.mapEq j u ∨ p.mapEq i u ∧ p.mapEq j l :=
  p.mergeLT_map_eq_iff h i j

end

section

variable {n : ℕ} (p : Partition n) (l u : Fin n)

def merge : Partition n :=
  p.splitOn l u (fun _ ↦ p) (fun h ↦ p.mergeLT h) (fun h ↦ p.mergeLT h)

theorem merge_mapEq_iff (i j : Fin n) :
    (p.merge l u).mapEq i j ↔
    p.mapEq i j ∨ p.mapEq i l ∧ p.mapEq j u ∨ p.mapEq i u ∧ p.mapEq j l := by
  apply p.splitOn l u
  · intro h₁
    rw [merge, p.splitOn_eq _ _ h₁]
    simp
    intro h
    apply h.elim
    · intro h₂
      exact h₂.left.trans (h₁.trans h₂.right.symm)
    · intro h₂
      exact h₂.left.trans (h₁.symm.trans h₂.right.symm)
  · intro h₁
    rw [merge, p.splitOn_lt _ _ h₁]
    exact p.mergeLT_mapEq_iff h₁ i j
  · intro h₁
    rw [merge, p.splitOn_gt _ _ h₁]
    conv_rhs => arg 2 ; rw [Or.comm]
    exact p.mergeLT_mapEq_iff h₁ i j

end

section

variable {n : ℕ} (p : Partition n) (r : Fin n → Fin n → Prop)

lemma merge_preserves_eqvGen_sound_of_rel (i j : Fin n) :
    p.sound (EqvGen r) → r i j → (p.merge i j).sound (EqvGen r)
  := by
    intro hs hr i' j' hp
    apply ((p.merge_mapEq_iff i j i' j').mp hp).elim (hs i' j' ·)
    intro h
    apply h.elim
    · intro ⟨h₁, h₂⟩
      apply EqvGen.trans _ _ _ (hs _ _ h₁)
      apply EqvGen.trans _ _ _ (EqvGen.rel _ _ hr)
      exact hs _ _ h₂.symm
    · intro ⟨h₁, h₂⟩
      apply EqvGen.trans _ _ _ (hs _ _ h₁)
      apply EqvGen.trans _ _ _ (EqvGen.symm _ _ (EqvGen.rel _ _ hr))
      exact hs _ _ h₂.symm

lemma merge_relaxes_weakend_exact_of_rel (i j : Fin n) :
    p.exact (weaken_rel r i.castSucc j.castSucc) → r i j →
    (p.merge i j).exact (weaken_rel r i.castSucc j.succ)
  := by
    intro he hr i' j' ⟨hw, hr'⟩
    apply (p.merge_mapEq_iff i j i' j').mpr
    apply hw.elim
    · intro hi
      exact Or.inl (he i' j' ⟨Or.inl hi, hr'⟩)
    · intro ⟨hi, hj⟩
      obtain rfl : i = i' := eq_of_val_eq hi.symm
      clear hi hw
      if hj' : j'.val = j.val then
        obtain rfl : j = j' := eq_of_val_eq hj'.symm
        exact Or.inr (Or.inl ⟨rfl, rfl⟩)
      else
        replace hj := (le_of_lt_succ hj).lt_of_ne hj'
        exact Or.inl (he i j' ⟨Or.inr ⟨rfl, hj⟩, hr'⟩)

lemma relaxes_weakend_exact_of_not_rel (i j : Fin n) :
    p.exact (weaken_rel r i.castSucc j.castSucc) → ¬ r i j →
    p.exact (weaken_rel r i.castSucc j.succ)
  := by
    intro he hr i' j' ⟨hw, hr'⟩
    apply hw.elim
    · intro hi
      exact he i' j' ⟨Or.inl hi, hr'⟩
    · intro ⟨hi, hj⟩
      obtain rfl : i = i' := eq_of_val_eq hi.symm
      clear hi hw
      if hj' : j'.val = j.val then
        obtain rfl : j = j' := eq_of_val_eq hj'.symm
        exact False.elim (hr hr')
      else
        exact he i j' ⟨Or.inr ⟨rfl, (le_of_lt_succ hj).lt_of_ne hj'⟩, hr'⟩

variable [∀ i j : Fin n, Decidable (r i j)] (i j : Fin n)

def conditional_merge : Partition n := if r i j then p.merge i j else p

lemma conditional_merge_preserves_eqvGen_sound :
    p.sound (EqvGen r) → (p.conditional_merge r i j).sound (EqvGen r)
  := by
    intro hs
    if hr : r i j then
      rw [conditional_merge, ite_cond_eq_true _ _ (eq_true_intro hr)]
      exact p.merge_preserves_eqvGen_sound_of_rel r i j hs hr
    else
      rw [conditional_merge, ite_cond_eq_false _ _ (eq_false_intro hr)]
      exact hs

lemma condition_merge_relaxes_weakened_exact :
    p.exact (weaken_rel r i.castSucc j.castSucc) →
    (p.conditional_merge r i j).exact (weaken_rel r i.castSucc j.succ)
  := by
    intro he
    if hr : r i j then
      rw [conditional_merge, ite_cond_eq_true _ _ (eq_true_intro hr)]
      exact p.merge_relaxes_weakend_exact_of_rel r i j he hr
    else
      rw [conditional_merge, ite_cond_eq_false _ _ (eq_false_intro hr)]
      exact p.relaxes_weakend_exact_of_not_rel r i j he hr

end

section

variable {n : ℕ} (p : Partition n)
variable (r : Fin n → Fin n → Prop) [∀ i j : Fin n, Decidable (r i j)]

def conditional_merge_rec₂ (i : Fin n) (j : ℕ) (h : j < n + 1) : Partition n :=
  match j with
  | 0 => p
  | j + 1 => (conditional_merge_rec₂ i j ((lt_succ_self _).trans h)).conditional_merge
    r i ⟨j, Nat.add_lt_add_iff_right.mp h⟩

def conditional_merge_rec₁ (i : ℕ) (h : i < n + 1) : Partition n :=
  match i with
  | 0 => p
  | i + 1 => (conditional_merge_rec₁ i ((lt_succ_self _).trans h)).conditional_merge_rec₂
    r ⟨i, Nat.add_lt_add_iff_right.mp h⟩ n (lt_succ_self n)

lemma conditional_merge_rec₂_preserves_eqvGen_sound (i : Fin n) (j : ℕ) (h : j < n + 1) :
    p.sound (EqvGen r) → (p.conditional_merge_rec₂ r i j h).sound (EqvGen r)
  := by
    intro hs
    induction j with
    | zero => exact hs
    | succ j ih => apply conditional_merge_preserves_eqvGen_sound ; apply ih

lemma conditional_merge_rec₁_preserves_eqvGen_sound (i : ℕ) (h : i < n + 1) :
    p.sound (EqvGen r) → (p.conditional_merge_rec₁ r i h).sound (EqvGen r)
  := by
    intro hs
    induction i with
    | zero => exact hs
    | succ i ih => apply conditional_merge_rec₂_preserves_eqvGen_sound ; apply ih

lemma conditional_merge_rec₂_relaxes_weakened_exact (i : Fin n) (j : ℕ) (h : j < n + 1) :
    p.exact (weaken_rel r i.castSucc 0) →
    (p.conditional_merge_rec₂ r i j h).exact (weaken_rel r i.castSucc ⟨j, h⟩)
  := by
    intro he
    induction j with
    | zero => exact he
    | succ j ih => apply condition_merge_relaxes_weakened_exact ; apply ih

lemma conditional_merge_rec₁_relaxes_weakened_exact (i : ℕ) (h : i < n + 1) :
    p.exact (weaken_rel r 0 0) → (p.conditional_merge_rec₁ r i h).exact (weaken_rel r ⟨i, h⟩ 0)
  := by
    intro he
    induction i with
    | zero => exact he
    | succ i ih =>
      apply lift_exact _ _ _ (fun _ _ ↦ (weaken_succ r ⟨i, Nat.add_lt_add_iff_right.mp h⟩ _ _).mpr)
      apply conditional_merge_rec₂_relaxes_weakened_exact ; apply ih

end

section

variable {n : ℕ} (r : Fin n → Fin n → Prop) [∀ i j : Fin n, Decidable (r i j)]

def of_relation : Partition n := (Partition.id n).conditional_merge_rec₁ r n (lt_succ_self n)

theorem of_relation_eqvGen_sound : (of_relation r).sound (EqvGen r) :=
  conditional_merge_rec₁_preserves_eqvGen_sound _ _ _ _ (id_eqvGen_sound _ _)

theorem of_relation_exact : (of_relation r).exact r :=
  lift_exact _ _ _ (fun _ _ ↦ (weaken_last _ _ _ _).mpr)
  (conditional_merge_rec₁_relaxes_weakened_exact _ _ _ _ (id_weaken_trivial_exact _ _))

theorem of_relation_eqvGen_exact : (of_relation r).exact (EqvGen r) :=
  eqvGen_exact_of_exact _ _ (of_relation_exact _)

theorem of_relation_iff_eqvGen : ∀ i j : Fin n, (of_relation r).mapEq i j ↔ EqvGen r i j :=
  fun i j ↦ ⟨of_relation_eqvGen_sound r i j, of_relation_eqvGen_exact r i j⟩

end

section

instance rel_decidable_of_partition {n : ℕ} (p : Partition n) (r : Fin n → Fin n → Prop)
    (h : ∀ i j : Fin n, p.mapEq i j ↔ r i j) (i j : Fin n) : Decidable (r i j) :=
  decidable_of_decidable_of_iff (h i j)

/-- The isomorphism between partitions and decidable equivalence relations. -/

theorem of_relation_mapEq_eq_eqvGen {n : ℕ} (r : Fin n → Fin n → Prop)
    [∀ i j : Fin n, Decidable (r i j)] : (of_relation r).mapEq = EqvGen r :=
  funext₂ <| fun _ _ ↦ propext <| of_relation_iff_eqvGen _ _ _

theorem of_eqv_relation_mapEq_id {n : ℕ} {r : Fin n → Fin n → Prop}
    (h : Equivalence r) [∀ i j : Fin n, Decidable (r i j)] : (of_relation r).mapEq = r :=
  (of_relation_mapEq_eq_eqvGen r).trans <| Equivalence.eqvGen_eq h

theorem mapEq_to_relation_id {n : ℕ} (p : Partition n) : of_relation p.mapEq = p := by
  ext i j
  apply Iff.intro _ (of_relation_exact p.mapEq i j)
  intro h
  exact Equivalence.eqvGen_eq p.mapEq_equivalence ▸ (of_relation_iff_eqvGen p.mapEq i j).mp h

end

end Partition

end Fin
